# Generated by Django 4.1 on 2023-04-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0002_players_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
