# Generated by Django 4.1 on 2023-04-29 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0003_alter_players_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='jersey',
        ),
    ]
