# Generated by Django 4.1 on 2023-04-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0004_remove_players_jersey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ee',
            name='x_coord_adj',
        ),
        migrations.RemoveField(
            model_name='ee',
            name='y_coord_adj',
        ),
        migrations.RemoveField(
            model_name='faceoffs',
            name='x_coord_adj',
        ),
        migrations.RemoveField(
            model_name='faceoffs',
            name='y_coord_adj',
        ),
        migrations.RemoveField(
            model_name='passes',
            name='passer_x_coord_adj',
        ),
        migrations.RemoveField(
            model_name='passes',
            name='passer_y_coord_adj',
        ),
        migrations.RemoveField(
            model_name='passes',
            name='receiver_x_coord_adj',
        ),
        migrations.RemoveField(
            model_name='passes',
            name='receiver_y_coord_adj',
        ),
        migrations.RemoveField(
            model_name='penalties',
            name='x_coord_adj',
        ),
        migrations.RemoveField(
            model_name='penalties',
            name='y_coord_adj',
        ),
        migrations.RemoveField(
            model_name='recoveries',
            name='x_coord_adj',
        ),
        migrations.RemoveField(
            model_name='recoveries',
            name='y_coord_adj',
        ),
        migrations.RemoveField(
            model_name='shots',
            name='x_coord_adj',
        ),
        migrations.RemoveField(
            model_name='shots',
            name='y_coord_adj',
        ),
        migrations.RemoveField(
            model_name='takeaways',
            name='x_coord_adj',
        ),
        migrations.RemoveField(
            model_name='takeaways',
            name='y_coord_adj',
        ),
    ]
