# Generated by Django 4.1 on 2023-04-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0005_remove_ee_x_coord_adj_remove_ee_y_coord_adj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shots',
            name='traffic',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
