# Generated by Django 4.1 on 2023-04-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0007_alter_shots_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passes',
            name='pass_type',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
