# Generated by Django 4.1 on 2023-04-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0008_alter_passes_pass_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceoffs',
            name='id',
            field=models.BigAutoField(auto_created=True, default=-1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faceoffs',
            name='faceoff_id',
            field=models.IntegerField(default=-1),
        ),
    ]
