# Generated by Django 4.1 on 2023-04-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0011_remove_playergame_ca_remove_playergame_cf_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergame',
            name='successful_passes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergame',
            name='total_passes',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
