# Generated by Django 4.1 on 2023-04-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0013_playertourney_successful_passes_gp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergame',
            name='dzfo_successful',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergame',
            name='dzfo_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergame',
            name='fo_successful',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergame',
            name='nzfo_successful',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergame',
            name='nzfo_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergame',
            name='ozfo_successful',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergame',
            name='ozfo_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playertourney',
            name='dzfo_successful_gp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playertourney',
            name='dzfo_taken_gp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playertourney',
            name='fo_successful_gp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playertourney',
            name='nzfo_successful_gp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playertourney',
            name='nzfo_taken_gp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playertourney',
            name='ozfo_successful_gp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playertourney',
            name='ozfo_taken_gp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
