# Generated by Django 4.1 on 2023-05-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0016_playertourney_shots_for_gp_percentile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtourney',
            name='gf_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamtourney',
            name='gf_percent_percentile',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
