# Generated by Django 4.1 on 2023-05-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0017_teamtourney_gf_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BokehData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event', models.CharField(blank=True, max_length=100, null=True)),
                ('Perspective', models.CharField(blank=True, max_length=100, null=True)),
                ('Game', models.CharField(blank=True, max_length=100, null=True)),
                ('Player', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('shape', models.CharField(blank=True, max_length=100, null=True)),
                ('Team', models.CharField(blank=True, max_length=100, null=True)),
                ('Details', models.CharField(blank=True, max_length=100, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('x1', models.FloatField(blank=True, null=True)),
                ('x2', models.FloatField(blank=True, null=True)),
                ('y1', models.FloatField(blank=True, null=True)),
                ('y2', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
